# Site Settings
name: Bioinformatics Guy
title: Bioinformatics Guy
description: Let's explore what is Bioinformatics.
tags:
  - Bioinformatics
  - Programming
  - Python
show_hero: true

menu:
  - title: Home
    url: /
  - title: About
    url: /about
  - title: Portfolio
    url: /portfolio
  - title: Contact
    url: /contact
email: bioinformaticsguy@gmail.com
disqus_username: bioinformaticsguy


# Social Media Settings
# Remove the item if you don't need it
github_username: bioinformaticsguy
facebook_username: groups/bioinformaticsguys
twitter_username: alihassan1697
instagram_username: alihassan1697
linkedin_username: alihassan1697
#medium_username: medium_username


# Posts Settings
show_time_bar: true
show_modal_on_exit: true
show_modal_on_finish_post: true
two_columns_layout: true 


# Advanced Settings
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
google_analytics: "UA-174162148-2"
language: "en"
categories_folder: category
sent_message_url: "/contact/message-sent/"


# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/
collections:
  authors:
    output: true
paginate_path: "/page/:num/"
show_get_theme_btn: false
use_logo: false


# Content paginator
paginate_content:
  enabled: false
  debug: false
  collections:
    - posts
  auto: true
  separator: "--page-break--"
  permalink: "/:num/"
  seo_canonical: true
  properties:
    part:
      is_generated: true
    last:
      is_generated: true
    single:
      is_generated: true

# SASS
sass:
  style: compressed

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-paginate-content

# Exclude my node related stuff
exclude: [
  'package.json',
  'package-lock.json',
  'src',
  'node_modules',
  'initpost.sh',
  'Gemfile',
  'Gemfile.lock',
  'gulpfile.js',
  'README.md'
]

# Theme
# version: v1.0
